#=============================================================
#             FOS Event Engine (Fortress TvT)
#=============================================================

# Enable/Disable FOSEvent System.
FOSEventEnabled = True

# Times FOS will occur (24h format).
FOSEventInterval = 11:00,15:00,17:00,23:00

# Registration timer from start of event (in minutes).
FOSEventParticipationTime = 5

# Event running time (in minutes).
FOSEventRunningTime = 10

# Location name of EventManager.
FOSNpcLocName = Giran Town

# FOS Event NPC (create a custom npc of type L2EventManager).
FOSEventParticipationNpcId = 10007

# FOS First Team Headquarters NPC (create a custom npc of type L2FOSFlag).
FOSEventArtifactNpcId = 65011

# FOS Event Participation Fee (itemId, number). Fee is not returned.
# Example: 57,10000
# Default = none
FOSEventParticipationFee = 0,0

# Fort Summon Skill learned during events
# Skill retail id: 246
FOSEventSummonSkillId = 9502

# Location for FOSEvent NPC to spawn in form x,y,z[,heading]
FOSEventParticipationNpcCoordinates = 82856,148626,-3469

# Location for summon Artifact NPC to spawn in form x,y,z[,heading]
FOSEventArtifactCoordinates = 154696,55464,-3096

# Minimum amount of players allowed in each team.
# Recommend not to set less that 2 on live servers,
# due to flag carriers are unable to cast offensive skills.
# You may alternatively set to 1 for testing purposes.
FOSEventMinPlayersInTeams = 1

# Max amount of players allowed in each team.
FOSEventMaxPlayersInTeams = 200

# Min/Max level of players that may join the event.
FOSEventMinPlayerLevel = 52
FOSEventMaxPlayerLevel = 85

# Respawn and exit delay timers (in seconds).
FOSEventRespawnTeleportDelay = 25
FOSEventStartLeaveTeleportDelay = 10

# First Team - Name, Start/Death x,y,z location - Flag x,y,z location.
FOSEventTeam1Name = Omega
FOSEventTeam1Coordinates = 152168,57672,-3280

# Second Team - Name, Start/Death x,y,z location - Flag x,y,z location.
FOSEventTeam2Name = Alpha
FOSEventTeam2Coordinates = 157544,53240,-3272

# Reward for winning team.
# Example: FOSEventRewardWinners = itemId,amount;itemId,amount;itemId,amount
FOSEventRewardWinners = 9501,75,75;9500,100000,100000;31001,1,1;9850,1,1,1;

# Reward for loser team.
# Example: FOSEventRewardLosers = itemId,amount;itemId,amount;itemId,amount
FOSEventRewardLosers = 9501,25,25;9500,50000,50000;

# FOSEvent Rules
FOSEventTargetTeamMembersAllowed = False
FOSEventScrollsAllowed = False
FOSEventPotionsAllowed = False
FOSEventSummonByItemAllowed = False

# Door ID's to open/close on start/end.
# Example: FOSDoorsToOpen = 1;2;3;4;5;6
FOSDoorsAttackable = 24190010;24190008;24190009;24190006;24190007;24190005

# Should both teams get reward if there's a tie?
FOSRewardTeamTie = True

# Participant's effects handling on teleport/death.
# Effects lasting through death never removed.
# 0 - always remove all effects.
# 1 - remove all effects only during port to event (noblesse blessing can be used)
# 2 - never remove any effect
# Default: 0
FOSEventEffectsRemoval = 2

# Fighter-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1501,1;1502,1;1499,1;1086,1
FOSEventFighterBuffs =

# Mage-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1500,1;1501,1;1085,3
FOSEventMageBuffs =

# Enabling this option will not be possible to register for the event with the specified number of Box.
# Default: True
FOSEventMultiBoxEnable = True

# Box number allowed inside the event.
# Default: 1
FOSEventNumberBoxRegister = 3

# Enabling rewarding disconected players
# Default: False
FOSRewardNoCarrierPlayers = True
