#=============================================================
#             Kill the Boss Event Engine
#=============================================================
# Enable/Disable KTBEvent System
KTBEventEnabled = False

# Times KTB will occur (24h format).
KTBEventInterval = 04:00,10:00,16:00,22:00

# Registration timer from start of event (in minutes).
KTBEventParticipationTime = 5

# Event running time (in minutes).
KTBEventRunningTime = 10

# Location name of EventManager.
KTBNpcLocName = Giran Town

# KTB Event NPC (create a custom npc of type L2EventManager).
KTBEventParticipationNpcId = 10007

# KTB Event Participation Fee (itemId, number). Fee is not returned.
# Example: 57,100000
# Default = none
KTBEventParticipationFee = 0,0

# Reward for winning team.
# Example: KTBEventReward = itemId,amount;itemId,amount;itemId,amount;...
KTBEventReward = 9501,50,50;9500,50000,50000;9850,1,1,1

# Location for KTBEvent NPC to spawn in form x,y,z[,heading]
KTBEventParticipationNpcCoordinates = 82856,148626,-3469

# KTB Event BOSS (create a custom npc of type L2RaidBoss or L2Monster).
KTBEventBossListId = 50050,50053,50058,50061,50064

# Location for KTBEvent Boss to spawn in form x,y,z[,heading]
KTBEventBossCoordinates = 169592,-91288,-2912

# Min/Max amount of players allowed in each team.
KTBEventMinPlayers = 1
KTBEventMaxPlayers = 300

# Min/Max level of players that may join the event.
KTBEventMinPlayerLevel = 1
KTBEventMaxPlayerLevel = 80

# Coordinates for the players spawn.
# Example: x1,y1,z1;x2,y2,z2;x3,y3,z3
KTBEventPlayerCoordinates = 170760,-91288,-2912;169592,-92472,-2912;168408,-91288,-2912;169592,-90104,-2912

# Repsawn and exit delay timers (in seconds).
KTBEventRespawnTeleportDelay = 10
KTBEventStartLeaveTeleportDelay = 10

# KTBEvent Rules
KTBEventScrollsAllowed = False
KTBEventPotionsAllowed = False
KTBEventSummonByItemAllowed = False

# Door ID's to open/close on start/end.
# Not supported in instance, use xml template for defining doors.
# Example: DMDoorsToOpen = 1;2;3;4;5;6
KTBDoorsToOpen = 24190001;24190002;24190003;24190004
KTBDoorsToClose = 24190001;24190002;24190003;24190004

# Participant's effects handling on teleport/death.
# Effects lasting through death never removed.
# 0 - always remove all effects.
# 1 - remove all effects only during port to event (noblesse blessing can be used)
# 2 - never remove any effect
# Default: 0
KTBEventEffectsRemoval = 2

# Fighter-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1501,1;1502,1;1499,1
KTBEventFighterBuffs =

# Mage-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1500,1;1501,1;1085,3
KTBEventMageBuffs =

# Enabling this option will not be possible to register for the event with the specified number of Box.
# Default: True
KTBEventMultiBoxEnable = True
# Box number allowed inside the event.
# Default: 1
KTBEventNumberBoxRegister = 3

# ID of classes that are not allowed to join the tvt
KTBDisabledForClasses = 16,97,30,105,43,112

# Enabling rewarding disconected players
# Default: False
KTBRewardNoCarrierPlayers = False