#=============================================================
#             Last Man Event Engine
#=============================================================
# Enable/Disable LMEvent System
LMEventEnabled = False

# Times LM will occur (24h format).
LMEventInterval = 15:00,21:00

# Registration timer from start of event.
# Model: hh:mm:ss
# Example: 00:05:00 - 05 minutes for the register.
# Default: 01:00:00 - 01 hours for the register.
LMEventParticipationTime = 00:05:00

# Event running time (in minutes).
LMEventRunningTime = 15

# How many times a player can die.
# This will be credited to your participation.
# Once finished the credits the player leaves the event.
LMEventPlayerCredits = 1

# Location name of EventManager.
LMNpcLocName = Giran Town

# LM Event NPC (create a custom npc of type L2EventManager).
LMEventParticipationNpcId = 10007

# LM Event Participation Fee (itemId, number). Fee is not returned.
# Example: 57,100000
# Default = none
LMEventParticipationFee = 9500,100

# Location for LMEvent NPC to spawn in form x,y,z[,heading]
LMEventParticipationNpcCoordinates = 82856,148626,-3469

# Min/Max amount of players allowed in each team.
LMEventMinPlayers = 2
LMEventMaxPlayers = 500

# Min/Max level of players that may join the event.
LMEventMinPlayerLevel = 1
LMEventMaxPlayerLevel = 80

# Coordinates for the players spawn.
# Example: x1,y1,z1;x2,y2,z2;x3,y3,z3
LMEventPlayerCoordinates = 58710,-27875,576;57583,-27190,576;57185,-27727,576;57192,-27172,586;56573,-27372,574;56881,-26711,574;56948,-25858,603;57958,-26796,600;57957,-26036,592;58944,-25914,592;58954,-26515,574;59152,-27676,560;58960,-28659,574;57958,-28243,602;56700,-27984,574;57038,-29078,568;

# Repsawn and exit delay timers (in seconds).
LMEventRespawnTeleportDelay = 10
LMEventStartLeaveTeleportDelay = 10

# Reward for winning players.
# Example: LMEventReward = itemId,amount;itemId,amount;itemId,amount
LMEventReward = 9501,50;9500,100000

# Should both players get reward if there's a tie?
LMRewardPlayersTie = False

# LMEvent Rules
LMEventScrollsAllowed = False
LMEventPotionsAllowed = False
LMEventSummonByItemAllowed = False

# Door ID's to open/close on start/end.
# Not supported in instance, use xml template for defining doors.
# Example: LMDoorsToOpen = 1;2;3;4;5;6
LMDoorsToOpen = 24190001;24190002;24190003;24190004
LMDoorsToClose = 24190001;24190002;24190003;24190004

# Participant's effects handling on teleport/death.
# Effects lasting through death never removed.
# 0 - always remove all effects.
# 1 - remove all effects only during port to event (noblesse blessing can be used)
# 2 - never remove any effect
# Default: 0
LMEventEffectsRemoval = 2

# Fighter-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1501,1;1502,1;1499,1
LMEventFighterBuffs =

# Mage-class participants will be buffed with those buffs each respawn
# Format: skill1Id,skill1Level;skill2Id,skill2Level...
# Example: 1504,1;1500,1;1501,1;1085,3
LMEventMageBuffs =

# Method to show player's kill on the TvT event.
# Choose "pm" for an automatic personal message to the player team.
# Example: "Player1: I have killed Player2 !".
# Put "title" for an automatic title that counts the player's kills.
# Example: "Kills: number" (title will be restored at the event end).
# Put "pmtitle" for both methods (pmtitle and title).
# Default: title
LMEventOnKill = title

# Enabling this option will not be possible to register for the event with the specified number of Box.
# Default: True
LMEventMultiBoxEnable = True
# Box number allowed inside the event.
# Default: 1
LMEventNumberBoxRegister = 3

# ID of classes that are not allowed to join the tvt
LMDisabledForClasses = 16,97,30,105,43,112