#=============================================================
#                  Change PvpZone Config
#=============================================================

# How Many Minutes To Change PvP Random Zone To Next Zone
# In Minutes: 60 = 1 Hour
ChangeZoneTime = 5

# Announcement Before PvPZone Changed.
# In Minutes
AnnounceTimer = 1

# Show a invite box for players
# System Mensage required
AllowDlgInvite = False

# Show a Vote Html all players
AllowVoteWindow = False

# If AnnouceTimer is 5 Use 2
# Default: 2 Minutes
VoteWindowTimer = 1

# Vote Window Shoe Again in minutes
# If ChangeZone is 60 use 45, 50 ,55
VoteWindowRestart = 5

# Server Name used on html
ServerName = L2WarZone

# WarBoss Spawn after Zone Seted
# In Minutes
WarBossSpawnTime = 1

# WarBoss ID List
WarBossIdList = 50050,50053,50058,50061,50064
