#=============================================================
#                    Hwid System Ban
#=============================================================
# Allow Guard Protection System
AllowGuardSystem = True

# Installing client HWID
# 1 = HWID HDD
# 2 = HWID MAC
# 3 = HWID CPU
# 4 = HWID PC-NAME
UseClientHWID = 1
KickWithEmptyHWID = False
KickWithLastErrorHWID = True

# Enable log on Console Server - Player, HWID, NAME, ID
EnableConsoleLog = True