#=============================================================
#                    Fake Player Features
#=============================================================

# Time of Fake Citizen will be spawned
FakeCitizenDespawnMinTime = 720
FakeCitizenDespawnMaxTime = 720

# Time of Fake PvP Player will be spawned
FakePvpDespawnMinTime = 720
FakePvpDespawnMaxTime = 720

# Chance of bot sit/run
FakeSocialChance = 1000000

# Chance of bot Sit and Stand on Peace Zone
FakeSitChance = 62000

# Chance of bot Talk on Peace Zone
FakeTalkChance = 0

# Chance of bot Talk on Die
FakeTalkChanceDied = 0

# Chance of bot Talk on Kill
FakeTalkChanceKilled = 0

# Fake Players clan list, its used by fake players
FakeClanIDList = 268563229,268563229

# If empty, color name will be load on fakeColornamewordlist.txt
FakePlayerColorName =

# If empty, color title will be load on fakeTitlenamewordlist.txt
FakePlayerColorTitle =

# If empty, tittle will be load on faketitlewordlist.txt
FakePlayerTitle =

# Private store Buy List
# Format: itemId,minbuy,maxbuy,minprice,maxprice,chanceTouse(%)(optional);itemId,minbuy,maxbuy,minprice,maxprice,chanceTouse(%)(optional).
FakePrivateBuyList = 6622,5,10,7500,5000,50;8762,5,10,7500,5000,40;9501,5,10,7500,5000,1;9502,5,10,7500,5000,90;

# Private store Sell List
# If the item is not stack, use min and max always 1.
# Format: itemId,minsell,maxsell,chanceTouse(%)(optional);itemId,minsell,maxsell,chanceTouse(%)(optional).
FakePrivateSellList = 7575,1,1,1;9500,1000,1200;

# NPC's who fake players talk, its by id,id
FakeRoamingNpcs = 100,101,102,103,104,1005,10001,10002

#=============================================================
#            Fake Player NPC and Interactions
#=============================================================

# Allow DEBUG
FakePlayerDebug = False

# How many times should phantoms check the following NPCs before they stop checking them.
FakeRoamingMaxWhChecks = 3
FakeRoamingMaxWhChecksDwarf = 8
FakeRoamingMaxShopChecks = 3
FakeRoamingMaxShopChecksDwarf = 5
FakeRoamingMaxTeleportChecks = 3
FakeRoamingMaxBufferChecks = 3
FakeRoamingMaxPlayerChecks = 3
FakeRoamingMaxPlayerStoreChecks = 3

# Chance between checks
# (L2WarehouseInstance) Chance in (%)
FakeWarehouseChecksChance = 1
# (L2MerchantInstance) Chance in (%)
FakeShopChecksChance = 1
# (L2TeleportInstance) Chance in (%)
FakeTeleportChecksChance = 0
# (L2BufferInstance) Chance in (%)
FakeBufferChecksChance = 1
# Sit & Stand Chance in (%)
FakeRelaxChecksChance = 1
# Walk Around Chance in (%)
FakeWalkAroundChecksChance = 1
# Player Around Chance in (%)
FakePlayerAroundChecksChance = 1
# Player Private Store Around Chance in (%)
FakePlayerStoreAroundChecksChance = 0

#=============================================================
#                    Fake Player Check Area
#=============================================================

# Enable / Disable Check Area
AllowFakePlayerCheck = True

# Time of Fake PvP Player will be spawned
FakeCheckStartTime = 1
FakeCheckRestartTime = 2

#=============================================================
#                    Fake Player Consumables
#=============================================================

# Arrow used by fake archers
FakePlayerArrow = 1345

# Soulshot used by fighter fake players
FakePlayerSoulShot = 1467

# Blessed Spirit Shot used by mage fake players
FakePlayerBlessedSoulShot = 3952

# Fake Potion Skills. Separeted by " , "
PotionSkills = 2005,2037,2166

#=============================================================
#               Amor/Jewel/Weapon Fake Enchant
#=============================================================

# Fake Player Enchants
# Min - Max Enchant Armors
MinEnchantAmor = 22
MaxEnchantAmor = 25

# Min - Max Enchant Weapons
MinEnchantWeapon = 22
MaxEnchantWeapon = 25

# Min - Max Enchant Jewels
MinEnchantJewel = 22
MaxEnchantJewel = 25

#=============================================================
#                      Fake Player Armor
#=============================================================

# Armor are choose randomly
# Make a set armor 1
ListRobeArmor1 = 9311,9310,9312,9313,9314,9601,9604

# Make a set armor 2
ListRobeArmor2 = 9311,9310,9312,9313,9314,9601,9604

# Make a set armor 3
ListRobeArmor3 = 9311,9310,9312,9313,9314,9601,9604

# Make a set armor 4
ListRobeArmor4 = 9311,9310,9312,9313,9314,9601,9604

#-------------------

# Make a set armor 1
ListHeavyArmor1 = 9301,9300,9302,9303,9304,9600,9602

# Make a set armor 2
ListHeavyArmor2 = 9301,9300,9302,9303,9304,9600,9602

# Make a set armor 3
ListHeavyArmor3 = 9301,9300,9302,9303,9304,9600,9602

# Make a set armor 4
ListHeavyArmor4 = 9301,9300,9302,9303,9304,9600,9602

#-------------------

# Make a set armor 1
ListLightArmor1 = 9306,9305,9307,9308,9309,9600,9603

# Make a set armor 2
ListLightArmor2 = 9306,9305,9307,9308,9309,9600,9603

# Make a set armor 3
ListLightArmor3 = 9306,9305,9307,9308,9309,9600,9603

# Make a set armor 4
ListLightArmor4 = 9306,9305,9307,9308,9309,9600,9603

#=============================================================
#                    Fake Player Weapons
#=============================================================

# Bow Weapons used by fake Archers. Separeted by " , "
# Archer AI Weapons
FakeBowIDList = 9411,9420

# Dagger AI Weapons
FakeDaggerIDList = 9414,9421

# Tanker AI Weapons
FakeSwordIDList = 9413,9422,9429

# Farmer AI Weapons
FakeSpearIDList = 4858,4859,4860

# Warrior AI (Gladiator) Weapons
FakeDualIDList = 9419

# Warrior AI (Tyrant) Weapons
FakeFistIDList = 9444

# Tanker AI (Destroyer) Weapons
FakeBigSwordIDList = 4724,4725,4723

# Nuker AI Weapons
FakeMagicWeaponIDList = 9410

# Nuker/Tanker AI Shield
FakeShieldIDList = 9907,9908,9909,9918,9923,9924,9925,9926,9927,9929

#=============================================================
#                  Fake Player Misc/Jewels
#=============================================================

# Jewels set are choose randomly
# Make a set jewels 1
JewelSetList1 = 6660,1;6658,1;6656,1;6659,1;6657,1;

# Make a set jewels 2
JewelSetList2 = 6660,1;6658,1;6656,1;6659,1;6657,1;

# Enable Hair accessory for fake players
# Get a randomly accessory. Separeted by " , "
AllowFakePlayerAccesory = True
FakeAccessoryIDList = 30038,30039,30040,30092,30093,30094,30000,30004,19077,19078,19079,19025,19026,19027
# Custom CAP by class
AllowFakePlayerAccesoryByClass = False

#=============================================================
#                  Fake Player Buffer List
#=============================================================

# Macro buffer by class from fake players
# Set Nuker mage buffers
NukerBufferList = 1204,1040,1035,1045,1036,1303,1085,1059,1078,1062,1243,264,267,268,304,349,273,276,365,1413,1391,4703,1270,306,308,307,1392,1393,1352,1353,1354,1323

# Set Archer buffers
ArcherBufferList = 1204,1068,1040,1035,1036,1045,1086,1077,1242,264,267,268,269,304,271,274,275,1363,1388,4699,270,306,308,307,1392,1393,1352,1353,1354,1323

# Set Daggers buffers
DaggerBufferList = 1204,1068,1040,1035,1036,1045,1086,1077,1242,264,267,268,269,304,271,274,275,1363,1388,4699,270,306,308,307,1392,1393,1352,1353,1354,1323

# Set Warrior buffers
WarriorBufferList = 1204,1068,1040,1035,1036,1045,1086,1077,1242,264,267,268,269,304,271,274,275,1363,1388,4699,270,306,308,307,1392,1393,1352,1353,1354,1323

# Set Tanker buffers
TankerBufferList = 1204,1068,1040,1035,1036,1045,1086,1077,1242,264,267,268,269,304,271,274,275,1363,1388,4699,270,306,308,307,1392,1393,1352,1353,1354,1323

# Set Random buffers
RandomBufferList = 1204,1068,1040,1035,1036,1045,1086,1077,1242,264,267,268,269,304,271,274,275,1363,1388,4699,270,306,308,307,1392,1393,1352,1353,1354,1323

#=============================================================
#                  Fake Player Henna Dye
#=============================================================

# Enable Henna Symbol for fake players
# Check Hennas ID's on henna.xml
AllowFakePlayerHenna = True

# Macro buffer by class from fake players
# Set Nuker mage buffers
NukerHennaList = 115,175,180

# Set Archer buffers
ArcherHennaList = 109,169,174

# Set Daggers buffers
DaggerHennaList = 169,174

# Set Warrior buffers
WarriorHennaList = 169,174

# Set Warrior buffers
TankerHennaList = 169,174

#=============================================================
#                  Fake Player Event's
#=============================================================

# Enable fake players o TvT Event
TvTAllowFakePlayer = True

# Random Max fake players on TvT Event
TvTFakePlayerCountMin = 30
TvTFakePlayerCountMax = 50

# Spawnspot of fake players
TvTFakePlayerSpawnLocs = -114584,-251256,-2992

# ----------------

# Enable fake players o CTF Event
CTFAllowFakePlayer = False

# Random Max fake players on CTF Event
CTFFakePlayerCountMin = 4
CTFFakePlayerCountMax = 4

# Spawnspot of fake players
CTFFakePlayerSpawnLocs = -114584,-251256,-2992

# ----------------

# Enable fake players o DM Event
DMAllowFakePlayer = True

# Random Max fake players on DM Event
DMFakePlayerCountMin = 30
DMFakePlayerCountMax = 50

# Spawnspot of fake players
DMFakePlayerSpawnLocs = -114584,-251256,-2992

# ----------------

# Enable fake players o LM Event
LMAllowFakePlayer = False

# Random Max fake players on LM Event
LMFakePlayerCountMin = 4
LMFakePlayerCountMax = 4

# Spawnspot of fake players
LMFakePlayerSpawnLocs = -114584,-251256,-2992

# ----------------

# Enable fake players o KTB Event
KTBAllowFakePlayer = False

# Random Max fake players on KTB Event
KTBFakePlayerCountMin = 8
KTBFakePlayerCountMax = 8

# Spawnspot of fake players
KTBFakePlayerSpawnLocs = -114584,-251256,-2992
